services:
  db:
    image: postgres:17
    container_name: postgres-docker-dev
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend_net
      
  flask:
    build: .
    container_name: flask-docker-dev
    working_dir: /src
    ports:
      - "5000:5000"
      - "5678:5678"
    depends_on:
      - db
    command: gunicorn -w 4 -b 0.0.0.0:8000 main:app
    env_file:
      - .env
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
    volumes:
      - ./src:/src
    networks:
      - backend_net
  vue:
    build: .
    image: node:22
    container_name: vue-docker-dev
    working_dir: /frontEnd
    ports:
      - "5173:5173" # Vite dev server
    command: sh -c "npm install && npm run build && npm run preview -- --host 0.0.0.0 --port=5173"
    volumes:
      - ./frontEnd:/frontEnd
    networks:
      - backend_net

  nginx:
      image: nginx:latest
      container_name: nginx-reverse-proxy
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      ports:
        - "80:80"
      depends_on:
        - flask
        - vue
      networks:
        - backend_net


volumes:
  postgres_data:

networks:
  backend_net:
    driver: bridge
