services:
  db:
    image: postgres:17
    container_name: postgres-docker-prod
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend_net
      
  flask:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: flask-docker-prod
    working_dir: /src
    ports:
      - "5000:5000"
      - "5678:5678"
    depends_on:
      - db
    command: flask run --host=0.0.0.0 --port=5000
    env_file:
      - .env
    environment:
      FLASK_APP: main.py
      FLASK_ENV: production
    volumes:
      - ./src:/src
    networks:
      - backend_net
  vue:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: node:22
    container_name: vue-docker-prod
    working_dir: /frontEnd
    ports:
      - "5173:5173" # Vite dev server
    command: sh -c "npm install && npm run build && npm run preview -- --host 0.0.0.0 --port=5173"
    volumes:
      - ./frontEnd:/frontEnd
    networks:
      - backend_net

volumes:
  postgres_data:

networks:
  backend_net:
    driver: bridge
