version: "3.9"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  flask:
    build: .
    container_name: flask-docker
    working_dir: /src
    ports:
      - "5000:5000"
      - "5678:5678"
    depends_on:
      - db
    command: gunicorn --reload -w 4 -b 0.0.0.0:5000 main:app
    env_file:
      - .env
    volumes:
      - ./src:/src

volumes:
  postgres_data:
