version: "3.9"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - backend_net

  flask:
    build: .
    container_name: flask-docker-dev
    working_dir: /src
    ports:
      - "5000:5000"
      - "5678:5678"
    depends_on:
      - db
    command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m flask run --host=0.0.0.0 --port=5000 --reload --extra-files src/
    env_file:
      - .env
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
    volumes:
      - ./src:/src:cached  # no macOS/Windows
      - ./src:/src:delegated  # pode melhorar performance
    networks:
      - backend_net

volumes:
  postgres_data:

networks:
  backend_net:
    driver: bridge