[build]
    publish = "frontEnd"

[functions]
  directory = "netlify/functions"

  [functions.python_bundler]
    command = "pip"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
