"""empty message

Revision ID: 71b321e8f380
Revises: 
Create Date: 2025-09-20 00:38:31.714194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b321e8f380'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lavoura_permanente',
    sa.Column('ano', sa.String(), nullable=False),
    sa.Column('sigla_uf', sa.String(), nullable=False),
    sa.Column('id_municipio', sa.String(), nullable=False),
    sa.Column('produto', sa.String(), nullable=False),
    sa.Column('area_destinada_colheita', sa.Numeric(), nullable=True),
    sa.Column('area_colhida', sa.Numeric(), nullable=True),
    sa.Column('quantidade_produzida', sa.Numeric(), nullable=True),
    sa.Column('rendimento_medio_producao', sa.Numeric(), nullable=True),
    sa.Column('valor_producao', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('ano', 'sigla_uf', 'id_municipio', 'produto')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('encrypted_password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('lavoura_permanente')
    # ### end Alembic commands ###
